version: '3.1'

services:
  db:
    image: mysql:5.7
    ports:
      - "3312:3306"
    environment:
      MYSQL_NAME: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_USER: "${DB_USER}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"